"""Baseline task states and their dashboard display labels."""


DONE_TASKS = {
    "foundation-01",
    "foundation-02",
    "foundation-03",
    "foundation-07",
    "foundation-08",
    "foundation-09",
    "memory-01",
    "memory-02",
    "memory-03",
    "memory-04",
    "memory-05",
    "memory-06",
    "memory-07",
    "memory-09",
    "perception-01",
    "perception-02",
    "perception-06",
    "perception-07",
    "decision-01",
    "decision-02",
    "decision-03",
    "decision-04",
    "decision-05",
    "decision-06",
    "decision-08",
    "decision-09",
    "decision-10",
    "safety-01",
    "safety-02",
    "safety-03",
    "safety-04",
    "safety-05",
    "safety-06",
    "safety-07",
    "safety-08",
    "safety-09",
    "safety-10",
    "action-03",
    "action-04",
    "action-05",
    "action-06",
    "action-07",
    "action-08",
    "dashboard-01",
    "dashboard-02",
    "dashboard-03",
    "dashboard-04",
    "dashboard-05",
    "dashboard-06",
    "dashboard-07",
    "dashboard-08",
    "dashboard-09",
    "dashboard-10",
}


DOING_TASKS = {
    "foundation-04",
    "foundation-05",
    "foundation-06",
    "foundation-10",
    "memory-08",
    "memory-10",
    "perception-03",
    "perception-04",
    "perception-05",
    "perception-08",
    "action-01",
    "action-02",
    "action-09",
    "action-10",
    "learning-01",
    "learning-02",
    "reflection-01",
    "reflection-07",
    "reflection-08",
    "reflection-09",
    "milestone-01",
    "milestone-02",
    "milestone-03",
    "milestone-04",
    "milestone-05",
    "milestone-06",
    "milestone-09",
}


BLOCKED_TASKS = {
    "perception-09",
    "perception-10",
    "learning-03",
    "learning-04",
    "learning-05",
    "learning-06",
    "learning-07",
    "learning-08",
    "learning-09",
    "learning-10",
    "reflection-02",
    "reflection-03",
    "reflection-04",
    "reflection-05",
    "reflection-06",
    "reflection-10",
    "milestone-07",
    "milestone-08",
    "milestone-10",
}


STATUS_LABELS = {
    "todo": "未开始",
    "doing": "进行中",
    "blocked": "受阻",
    "done": "已完成",
    "skipped": "已跳过",
    "cancelled": "已取消",
}
