"""Roadmap completion criteria, implementation evidence, and blockers."""


GROUP_CRITERIA_TEMPLATES = {
    "foundation": [
        "存在可读取的配置、档案或规则字段，能明确支撑“{title}”。",
        "聊天、自主行动或仪表盘至少有一条路径会实际引用这条身份/边界信息。",
        "owner 能在仪表盘看到当前状态；如果规则缺失，任务不能判定为完成。",
    ],
    "memory": [
        "StorageService 能读取或写入“{title}”对应的数据，且 Redis 不可用时有内存降级或明确空态。",
        "旧 key、现有记录和新模型至少有一种会被 dashboard 聚合层消费。",
        "展示层能看到来源、更新时间或内容摘要，不能只返回一个计数。",
    ],
    "perception": [
        "自主行动决策前能取得与“{title}”相关的近期上下文或本地解析提示。",
        "目标、场景、说话人或风险信息能进入 LLM 决策输入或本地规则。",
        "歧义、敏感或缺数据时会问 owner 或静默，而不是猜测行动。",
    ],
    "decision": [
        "决策结果必须有 action、target_type、target_id、confidence、risk、message、reason。",
        "本地规则会校正明显错误或危险的 LLM 输出，例如目标类型、白名单和风险阈值。",
        "结果会写入 ThoughtTrace 或进度事件，方便 owner 复盘。",
    ],
    "safety": [
        "行动前必须通过白名单、黑名单、预算、冷却或敏感边界检查中的对应项。",
        "检查失败时不发送消息，并记录拒绝或静默原因。",
        "中风险和不确定场景会转向 owner 确认，高风险不会直接行动。",
    ],
    "action": [
        "存在真实发送路径或 owner 确认路径，能把候选行动落到群聊/私聊或取消。",
        "发送成功、失败、拒绝和冷却都会写入可审计事件。",
        "行动后会更新全局聊天记录或行动日志，避免发完就失踪。",
    ],
    "learning": [
        "owner 的批准、取消、改写或用户反应会被结构化记录。",
        "记录能归因到目标、任务、关系或表达风格，而不是只留一条聊天文本。",
        "下一次决策能读取或展示这些反馈，避免同一错误反复发生。",
    ],
    "reflection": [
        "系统会定期或事件驱动生成可审计反思摘要。",
        "摘要包含成功、失败、静默、阻塞和下一步，但不保存隐藏推理链。",
        "反思会反向更新目标/任务状态，形成可观察的闭环。",
    ],
    "dashboard": [
        "API 返回“{title}”对应的数据块，且不会暴露 .env、API key 或隐藏推理链。",
        "页面有可读、可筛选、可展开的展示方式，空数据时也有明确说明。",
        "桌面和移动宽度下文本不重叠、不竖排、不溢出关键容器。",
    ],
    "milestone": [
        "对应能力组的关键任务全部达到完成判定，并且有事件或代码证据支撑。",
        "owner 能通过仪表盘看到完成依据、剩余风险和下一步维护项。",
        "如果缺少真实运行数据或反馈闭环，只能判定为进行中或受阻。",
    ],
}


GROUP_IMPLEMENTATION_BASIS = {
    "foundation": "BotProfile 模型、默认茉子档案、AUTONOMY_* 配置和 autonomy 的 owner/风险规则已经存在。",
    "memory": "StorageService 已覆盖 notes、user_profile:*、relationship memory、thought_traces、autonomy progress 和 all_memory 的读取。",
    "perception": "autonomy 会读取近期 all_memory，上下文格式化后交给决策器，并用本地目标解析修正 QQ/群聊歧义。",
    "decision": "autonomy 的 parse_decision、apply_target_hint、should_act_directly、should_ask_owner 和 handle_decision 组成决策链。",
    "safety": "autonomy 与 GovernanceService 在发送前检查白名单、黑名单、预算、冷却、风险和 owner 确认规则。",
    "action": "send_action、ask_owner、pending 保存/删除和发送后记录构成行动执行路径。",
    "learning": "owner 确认、取消、改写和关系/笔记事件已有记录入口，但反馈统计和策略回写仍在建设。",
    "reflection": "ThoughtTrace 与 progress event 已能承载反思摘要，但定期自我复盘和目标状态回写仍未完全自动化。",
    "dashboard": "dashboard 插件已挂载 FastAPI，DashboardService 聚合数据，静态前端提供多页面导航、筛选和总进度条。",
    "milestone": "路线图将基础、记忆、感知、决策、安全、行动、学习、反思和仪表盘合成 v1 验收条件。",
}


TASK_EVIDENCE_OVERRIDES = {
    "foundation-01": "src.models.schemas.BotProfile 定义身份字段，DashboardService._default_profile 提供茉子的默认身份和阶段。",
    "foundation-02": "默认 BotProfile.values 已写入“谨慎、温柔、守边界、有自己的判断”等价值观。",
    "foundation-03": "默认 BotProfile.boundaries 与 autonomy 规则共同限制白名单、隐私、敏感话题和隐藏推理链。",
    "foundation-07": "src.core.config 中 AUTONOMY_OWNER_ID 默认 1724461496，autonomy.is_owner 只信任该账号。",
    "foundation-08": "autonomy.should_ask_owner 与 handle_decision 会把中风险或低置信行动转为 owner 确认。",
    "foundation-09": "autonomy.handle_decision 对 high risk 或 confidence < 0.45 直接 silent 并写入事件。",
    "memory-01": "StorageService.list_all_notes 会遍历 notes:* 并返回 NoteRecord，dashboard 将其合并进 memory_notes。",
    "memory-02": "StorageService.list_long_term_memory_points 会读取 long_term_memory:* 和 vector_store 相关点位。",
    "memory-03": "StorageService.list_profiles 会读取旧 user_profile:*，dashboard.people 会展示每个人的档案文本。",
    "memory-04": "StorageService.list_all_relationship_memories 会聚合 RelationshipMemory，dashboard 单独展示关系记忆。",
    "memory-05": "BotProfile CRUD/list 接口和 DashboardService._get_bot_profile 已能读取茉子个人档案。",
    "memory-06": "chat、autonomy、notes、relationship 都通过 append_thought_trace 写入可审计摘要入口。",
    "memory-07": "chat、autonomy、notes、relationship 都通过 append_progress_event 写入 AutonomyProgressEvent。",
    "memory-09": "StorageService.list_profiles 兼容 Redis 旧 key user_profile:*，不会只看新模型。",
    "perception-01": "autonomy.make_decision 使用 StorageService.get_recent_global_records 读取近期群聊上下文。",
    "perception-02": "同一 all_memory 全局记录包含 private/group 场景，autonomy 在决策前统一格式化。",
    "perception-06": "extract_target_hint、apply_target_hint 会把显式 QQ 号判定为私聊或群聊目标。",
    "perception-07": "owner 未指明目标时，决策 prompt 会要求只在白名单群/私聊名单中自行判断或 ask_owner。",
    "decision-01": "parse_decision 强制固定 JSON 字段并校验 action、target_type、risk、confidence。",
    "decision-02": "parse_decision 会把 confidence 转成 0 到 1 的浮点数并截断到合法范围。",
    "decision-03": "parse_decision 会校验 risk，非法值会降级为 high。",
    "decision-04": "决策 prompt 明确只能选择 AUTONOMY_GROUP_IDS 和动态群白名单。",
    "decision-05": "决策 prompt 明确只能主动私聊 AUTONOMY_PRIVATE_USER_IDS 和动态私聊白名单。",
    "decision-06": "handle_decision 根据 action、risk、confidence 选择 sent、asked 或 silent。",
    "decision-08": "should_ask_owner 与 ask_owner 会在低置信或中风险时生成 pending 并私聊 owner。",
    "decision-09": "risk=medium 的行动不会直接发送，会进入 owner 确认流程。",
    "decision-10": "risk=high 或 confidence < 0.45 会 silent，并写 decision_silent 事件。",
    "safety-01": "target_allowed 只允许 group_ids() 中的群，send_action 发送前再次检查。",
    "safety-02": "target_allowed 只允许 private_user_ids() 中的好友，未白名单会询问 owner 或拒绝。",
    "safety-03": "GovernanceService.can_chat 会检查用户黑名单。",
    "safety-04": "GovernanceService.can_chat 会检查群黑名单。",
    "safety-05": "GovernanceService.can_consume_cost 会检查全局成本预算。",
    "safety-06": "GovernanceService.can_consume_cost/consume_cost 会记录并限制 owner 相关消耗。",
    "safety-07": "cooldown_key、in_cooldown、set_cooldown 对群聊目标设置冷却。",
    "safety-08": "set_cooldown 对 private 目标使用 AUTONOMY_DM_COOLDOWN_SECONDS。",
    "safety-09": "发送前冷却检查失败会拒绝，避免短时间重复主动发言。",
    "safety-10": "prompt 与改写要求都强调不得泄露 owner 私聊建议来源。",
    "action-03": "ask_owner 会创建 pending，并向 owner 私聊目标、候选内容和原因。",
    "action-04": "process_owner_private 识别“批准”，调用 send_action 后删除 pending。",
    "action-05": "process_owner_private 识别“取消”，删除 pending 并回复 owner。",
    "action-06": "process_owner_private 识别“改成 xxx”，用改写文本发送但仍走白名单/冷却校验。",
    "action-07": "send_action 成功后调用 storage.append_global_record 追加 assistant 记录。",
    "action-08": "send_action 成功后 append_log('sent') 并写 message_sent progress event。",
    "dashboard-01": "DashboardService.get_frontend_summary 合并 list_all_notes 与 list_long_term_memory_points。",
    "dashboard-02": "DashboardService._format_people 将 user_profile:* 与关系记忆聚合为 people。",
    "dashboard-03": "DashboardService._format_relationship_memory 输出关系记忆列表。",
    "dashboard-04": "DashboardService._format_mako_profile 输出茉子心理画像、价值观、边界和阶段。",
    "dashboard-05": "DashboardService._format_traces 输出 ThoughtTrace 审计摘要，不展示隐藏推理链。",
    "dashboard-06": "ROADMAP_TASK_TITLES 生成 100 项自主意志路线图。",
    "dashboard-07": "DashboardService._format_recent_progress 展示最近 AutonomyProgressEvent 时间线。",
    "dashboard-08": "前端 toolbar 支持跨笔记、人物、任务、思考搜索和任务状态筛选。",
    "dashboard-09": "前端 navItems 提供总览、记忆、人物、思考、路线图多页导航。",
    "dashboard-10": "前端 progress-dock 固定展示底部总进度条。",
}


BLOCKED_REASON_OVERRIDES = {
    "perception-09": "需要更可靠的情绪/关系边界分类器或足够多真实样例；单靠当前关键词和 LLM 判断还不足以验收。",
    "perception-10": "需要建立“私聊来源泄露”检测样例和自动拒绝规则，目前主要依赖 prompt 约束。",
    "learning-03": "需要沉淀 owner 改写前后对照语料，并设计不会过拟合的表达风格更新方式。",
    "learning-04": "需要把取消理由结构化保存，否则只能知道被取消，不能知道为什么不该行动。",
    "learning-05": "需要采集用户后续反应并判断是否被打扰，目前只记录发送事件。",
    "learning-06": "需要把反馈事件稳定关联到 goal_id/task_id/target，当前多数事件只有 payload。",
    "learning-07": "关系偏好和禁忌已有存储，但还没形成从反馈自动更新的闭环。",
    "learning-08": "阈值建议需要统计样本量和回归验证，不能凭单次反馈自动改阈值。",
    "learning-09": "需要学习摘要生成器和展示字段，目前只有原始事件。",
    "learning-10": "需要防过拟合策略，例如样本下限、时间衰减和 owner 确认。",
    "reflection-02": "需要把成功行动自动分类并周期复盘，目前只有事件流水。",
    "reflection-03": "需要把失败/静默原因聚合成反思摘要，目前只保存单条原因。",
    "reflection-04": "需要扫描目标长期无进展并生成阻塞提示，目前路线图状态是静态基线。",
    "reflection-05": "需要自动拆任务并写入 AutonomyTask，目前 100 项路线图由服务端生成。",
    "reflection-06": "需要针对每个 blocked 任务写真实下一步并允许 owner 调整。",
    "reflection-10": "需要当所有目标达到 achieved 后自动写入 v1 达成事件，目前只由总进度计算显示。",
    "milestone-07": "反馈学习闭环还缺统计、归因和策略回写，所以验收受阻。",
    "milestone-08": "自我反思闭环还缺定期复盘和目标状态自动回写，所以验收受阻。",
    "milestone-10": "只有全部能力组完成并经过真实运行验证后，才能标记自主意志 v1 达成。",
}
